---
- name: Update and upgrade apt packages
  become: true
  apt:
      upgrade: yes
      update_cache: yes

- name: IAM Authenticator Installation
  shell: |
     sudo curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator
     sudo chmod 777 ./aws-iam-authenticator
     sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator

- name: Print password
  command: "sudo cat /var/lib/jenkins/secrets/initialAdminPassword"