---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Values.namespace.name }}
  labels:
    app: kibana
spec:
  type: LoadBalancer
  ports:
  - port: 5601
  selector:
    app: kibana